/*
    Copyright 2006 IT Practice A/S
    Copyright 2006 TDC Totalløsninger A/S
    Copyright 2006 Jens Bo Friis
    Copyright 2006 Preben Rosendal Valeur
    Copyright 2006 Carsten Raskgaard


    This file is part of OpenSign.

    OpenSign is free software; you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation; either version 2.1 of the License, or
    (at your option) any later version.

    OpenSign is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with OpenOcesAPI; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


    Note to developers:
    If you add code to this file, please take a minute to add an additional
    copyright statement above and an additional
    @author statement below.
*/

/* $Id: XMLDisplay.java,v 1.4 2012/09/27 11:03:50 pakj Exp $ */

package org.openoces.opensign.demo.servlets;

import org.openoces.opensign.demo.utils.Base64;

import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.ServletException;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * This class implements a servlet used to display the raw signature generated by OpenSign.
 * It is used in the demo setup on www.openoces.org.
 *
 * @author Carsten Raskgaard  <carsten@raskgaard.dk>
 *
 */

public class XMLDisplay extends HttpServlet {
	private static final long serialVersionUID = 8617006649779741270L;

	public void doPost(HttpServletRequest request,
                      HttpServletResponse response)
            throws IOException, ServletException {

        response.setContentType("text/xml");
        PrintWriter out = response.getWriter();
        String xml = request.getParameter("xml");
        out.println(Base64.base64Decode(xml.getBytes()));
    }
}